# -*- coding: utf-8 -*-
"""BTL_NDKM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rg4gF77B2oBZqdkroAanzBO4h0ZZqkPo
"""

!pip install -q mtcnn scikit-learn opencv-python-headless==4.9.0.80 matplotlib tensorflow seaborn

from google.colab import drive
drive.mount('/content/drive')

import os
DATASET_DIR = '/content/drive/MyDrive/DuLieuND'
FACE_DIR = '/content/drive/MyDrive/face_dataset'
MODEL_DIR = '/content/drive/MyDrive/face_models_facenet'
os.makedirs(FACE_DIR, exist_ok=True)
os.makedirs(MODEL_DIR, exist_ok=True)

print("Đường dẫn dữ liệu:", DATASET_DIR)
print("Thư mục lưu khuôn mặt:", FACE_DIR)
print("Thư mục lưu mô hình:", MODEL_DIR)

!pip install numpy==1.26.4

import numpy as np
print(np.__version__)

import matplotlib.pyplot as plt, cv2, random
people = sorted(os.listdir(DATASET_DIR))
print("Danh sách người:", people)
for person in people:
    path = os.path.join(DATASET_DIR, person)
    img_file = random.choice(os.listdir(path))
    img = cv2.imread(os.path.join(path, img_file))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img)
    plt.title(person)
    plt.axis('off')
    plt.show()

# 3.2.1 Phát hiện khuôn mặt bằng MTCNN
from mtcnn.mtcnn import MTCNN
import cv2, matplotlib.pyplot as plt, random, os

people = sorted(os.listdir(DATASET_DIR))
person = random.choice(people)
person_dir = os.path.join(DATASET_DIR, person)
img_files = [f for f in os.listdir(person_dir) if f.lower().endswith(('jpg','jpeg','png'))]
img_path = os.path.join(person_dir, random.choice(img_files))

print(f"Đang thử ảnh của: {person}")
print(f"Đường dẫn ảnh: {img_path}")

img = cv2.imread(img_path)
if img is None:
    raise FileNotFoundError(f"Không đọc được ảnh: {img_path}")

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
detector = MTCNN()
faces = detector.detect_faces(img_rgb)

for f in faces:
    x, y, w, h = f['box']
    x, y = max(0, x), max(0, y)
    cv2.rectangle(img_rgb, (x, y), (x+w, y+h), (0,255,0), 3)
    cv2.putText(img_rgb, f"{f['confidence']:.2f}", (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,0,0), 2)

plt.imshow(img_rgb)
plt.axis('off')
plt.title(f"Phát hiện {len(faces)} khuôn mặt – {person}")
plt.show()

# 3.2.2 Cắt và lưu khuôn mặt đã phát hiện
import os, cv2
from mtcnn.mtcnn import MTCNN

detector = MTCNN()
img = cv2.imread(img_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
results = detector.detect_faces(img_rgb)

os.makedirs(FACE_DIR, exist_ok=True)
count = 0
for i, r in enumerate(results):
    if r['confidence'] < 0.6: continue
    x,y,w,h = r['box']; x,y = max(0,x), max(0,y)
    face = img_rgb[y:y+h, x:x+w]
    face = cv2.resize(face, (160,160))
    out_path = os.path.join(FACE_DIR, f"face_{i}.jpg")
    cv2.imwrite(out_path, cv2.cvtColor(face, cv2.COLOR_RGB2BGR))
    count += 1

print(f"Đã cắt và lưu {count} khuôn mặt vào {FACE_DIR}")
plt.imshow(face)
plt.title("Ví dụ khuôn mặt đã cắt")
plt.axis('off')
plt.show()

# 3.2.3 Tạo dataset khuôn mặt chuẩn hóa cho toàn bộ dữ liệu
from mtcnn.mtcnn import MTCNN
import numpy as np, cv2, glob

detector = MTCNN()
total = 0
for person in people:
    src_dir = os.path.join(DATASET_DIR, person)
    dst_dir = os.path.join(FACE_DIR, person)
    os.makedirs(dst_dir, exist_ok=True)
    count = 0
    for ext in ('*.jpg','*.jpeg','*.png'):
        for fpath in glob.glob(os.path.join(src_dir, ext)):
            img = cv2.imread(fpath)
            if img is None: continue
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            res = detector.detect_faces(img_rgb)
            if not res: continue
            r = max(res, key=lambda r: r['confidence'])
            if r['confidence'] < 0.6: continue
            x,y,w,h = r['box']; x,y = max(0,x), max(0,y)
            face = img_rgb[y:y+h, x:x+w]
            if face.size==0: continue
            face = cv2.resize(face, (160,160))
            cv2.imwrite(os.path.join(dst_dir, os.path.basename(fpath)), cv2.cvtColor(face, cv2.COLOR_RGB2BGR))
            count += 1
            total += 1
    print(f"{person}: {count} ảnh khuôn mặt")
print(" Tổng số khuôn mặt đã tạo:", total)

!pip uninstall -y deepface
!pip install deepface==0.0.79 -q

!mkdir -p /root/.deepface/weights

from deepface.basemodels import Facenet
facenet = Facenet.loadModel()
print("Đã tải FaceNet thành công – output:", facenet.output_shape)

from google.colab import drive
drive.mount('/content/drive')

!cp /root/.deepface/weights/facenet_weights.h5 /content/drive/MyDrive/facenet_weights.h5

# 3.3.2 – Sinh embedding từ ảnh khuôn mặt
import numpy as np, cv2, os, time
from numpy.linalg import norm

def preprocess_face(img):
    img = cv2.resize(img, (160, 160))
    img = img.astype('float32')
    mean, std = img.mean(), img.std()
    img = (img - mean) / (std + 1e-6)
    return np.expand_dims(img, axis=0)

def get_embedding(face):
    emb = facenet.predict(preprocess_face(face), verbose=0)[0]
    return emb / norm(emb)

# --- Sinh toàn bộ embedding ---
start = time.time()
X_emb, Y_lbl = [], []

for person in sorted(os.listdir(FACE_DIR)):
    pdir = os.path.join(FACE_DIR, person)
    if not os.path.isdir(pdir): continue
    imgs = [os.path.join(pdir,f) for f in os.listdir(pdir) if f.lower().endswith(('jpg','jpeg','png'))]
    for fpath in imgs:
        img = cv2.imread(fpath)
        if img is None: continue
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        emb = get_embedding(img_rgb)
        X_emb.append(emb)
        Y_lbl.append(person)
    print(f"{person}: {len(imgs)} ảnh xử lý xong.")

X_emb = np.asarray(X_emb)
Y_lbl = np.asarray(Y_lbl)
np.savez_compressed(os.path.join(MODEL_DIR, 'faces_embeddings_facenet.npz'), embeddings=X_emb, labels=Y_lbl)

print(f"Tổng cộng {len(X_emb)} embedding – thời gian {time.time()-start:.1f}s")

data = np.load(os.path.join(MODEL_DIR, 'faces_embeddings_facenet.npz'))
X_emb = data['embeddings']
Y_lbl = data['labels']

print("Số lượng embedding:", X_emb.shape)
for i in range(min(5, len(X_emb))):
    print(f"{Y_lbl[i]} → vector[0:10]: {X_emb[i][:10]}")
    print("Độ dài vector:", np.linalg.norm(X_emb[i]))

import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Nạp embedding
data = np.load(os.path.join(MODEL_DIR, 'faces_embeddings_facenet.npz'))
X = data['embeddings']
Y = data['labels']

le = LabelEncoder()
y = le.fit_transform(Y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

clf = SVC(kernel='linear', probability=True)
clf.fit(X_train, y_train)

# Đánh giá
y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)

train_acc = accuracy_score(y_train, y_pred_train)
test_acc = accuracy_score(y_test, y_pred_test)
print(f"Train acc: {train_acc:.4f}, Test acc: {test_acc:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred_test, target_names=le.classes_))

# Hiển thị confusion matrix
cm = confusion_matrix(y_test, y_pred_test)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title("Ma trận nhầm lẫn (Test)")
plt.xlabel("Dự đoán")
plt.ylabel("Thực tế")
plt.show()

# Lưu mô hình
with open(os.path.join(MODEL_DIR, 'svm_facenet.pkl'), 'wb') as f:
    pickle.dump(clf, f)
with open(os.path.join(MODEL_DIR, 'label_encoder_facenet.pkl'), 'wb') as f:
    pickle.dump(le, f)
print("Đã lưu mô hình và label encoder vào", MODEL_DIR)

import random

# Nạp lại mô hình
with open(os.path.join(MODEL_DIR, 'svm_facenet.pkl'), 'rb') as f:
    clf = pickle.load(f)
with open(os.path.join(MODEL_DIR, 'label_encoder_facenet.pkl'), 'rb') as f:
    le = pickle.load(f)

# Chọn ảnh ngẫu nhiên trong FACE_DIR
person = random.choice(sorted(os.listdir(FACE_DIR)))
pdir = os.path.join(FACE_DIR, person)
img_file = random.choice([f for f in os.listdir(pdir) if f.lower().endswith(('jpg','jpeg','png'))])
img_path = os.path.join(pdir, img_file)

print(f" Ảnh test: {person}/{img_file}")

img = cv2.imread(img_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
emb = get_embedding(img_rgb).reshape(1,-1)
pred = clf.predict(emb)[0]
prob = clf.predict_proba(emb)[0][pred]
name = le.inverse_transform([pred])[0]

plt.imshow(img_rgb)
plt.axis('off')
plt.title(f"Dự đoán: {name} ({prob*100:.1f}%) — Thực tế: {person}")
plt.show()

# 3.5.2 – Test ảnh mới, có phát hiện khuôn mặt bằng MTCNN
from google.colab import files
from mtcnn.mtcnn import MTCNN
import cv2, numpy as np, matplotlib.pyplot as plt

uploaded = files.upload()
THRESHOLD = 0.55  # ngưỡng tin cậy
detector = MTCNN()

for fn in uploaded.keys():
    img = cv2.imread(fn)
    if img is None:
        print("Không đọc được ảnh:", fn)
        continue

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    faces = detector.detect_faces(img_rgb)

    if len(faces) == 0:
        print("Không phát hiện khuôn mặt nào trong ảnh:", fn)
        continue

    for f in faces:
        x, y, w, h = f['box']
        x, y = max(0, x), max(0, y)
        face_crop = img_rgb[y:y+h, x:x+w]

        emb = get_embedding(face_crop).reshape(1, -1)
        probs = clf.predict_proba(emb)[0]
        pred = np.argmax(probs)
        prob = probs[pred]
        name = le.inverse_transform([pred])[0]

        if prob < THRESHOLD:
            label = "Unknown"
            color = (255, 0, 0)
        else:
            label = name
            color = (0, 255, 0)

        # Vẽ khung khuôn mặt + nhãn
        cv2.rectangle(img_rgb, (x, y), (x + w, y + h), color, 3)
        cv2.putText(img_rgb, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)

    plt.imshow(img_rgb)
    plt.axis('off')
    plt.title(f"Kết quả nhận diện cho {fn}")
    plt.show()

print("📈 Tổng kết:")
print(f"Train Accuracy: {train_acc:.2%}")
print(f"Test Accuracy:  {test_acc:.2%}")

if test_acc > 0.9:
    print(" Mô hình hoạt động rất tốt (FaceNet + SVM).")
elif test_acc > 0.7:
    print("Mô hình đạt mức trung bình, có thể cần thêm dữ liệu huấn luyện.")
else:
    print(" Mô hình chưa học tốt – kiểm tra lại dữ liệu hoặc ảnh crop.")